#! /usr/bin/env perl

use strict;
use warnings;
# use Carp::Always;

# use FindBin;
# use lib "$FindBin::Bin";
# use Xyzzy;

use constant { TRUE => 1, FALSE => 0 };

my $fh;

while (<STDIN>) {
  chomp;
  $_ =~ s/\r+//;
  if ( /^>([^ |]*)/ ) {
    if (defined($fh)) {
      close $fh || die;
    }
    my $name = $1;
    ($name ne "") || die;
    my $filename = $name.".fasta";
    open($fh,">",$filename);
  }
  (defined($fh)) || die;
  print $fh $_,"\n";
}

if (defined($fh)) {
  close $fh || die;
}
